load_paths:
  - lib/assets/javascripts
  - lib/assets/stylesheets
  - spec/javascripts/
  - turbolinks-source: lib/assets/javascripts
  - jquery-rails: vendor/assets/javascripts
  - lodash-rails: vendor/assets/javascripts
  - normalize-rails: vendor/assets/javascripts

logical_paths:
  - tao.css
  - tao.js
  - test.js
