load_paths:
  - lib/assets/javascripts
  - lib/assets/stylesheets
  - vendor/assets/javascripts
  - vendor/assets/stylesheets
  - test/javascripts/
  - turbolinks-source: lib/assets/javascripts
  - jquery-rails: vendor/assets/javascripts
  - lodash-rails: vendor/assets/javascripts

logical_paths:
  - tao.css
  - tao.js
  - tao_test.js

build:
  logical_paths:
    - tao.js
    - tao.css
  path: dist

plugins:
  sauce_labs:
    tunnel_timeout: 120
    tunnel_args:
      - '-B'
      - 'all'
    browsers:
      Google Chrome:
        os: Mac, Windows
        version: -1
      Firefox:
        os: Mac, Windows
        version: -1
      Safari:
        platform: Mac
        version: -1
      iPhone:
        version: [9.3, 7.0]
      Motorola Droid 4 Emulator:
        version: [5.1, 4.4]
